import { Geist, Geist_Mono, Outfit, Rubik } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Rubik({
  variable: "--font-geist-mono",
  weight:'800',
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Providers> {children}</Providers>
      </body>
    </html>
  );
}
